# Generated by Django 4.2.18 on 2025-01-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomeinfo',
            name='contact_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='welcomeinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='welcomeinfo',
            name='welcome_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
