# Generated by Django 4.2.18 on 2025-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_alter_welcomeinfo_contact_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcomeinfo',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='welcomeinfo',
            name='welcome_title',
        ),
        migrations.AddField(
            model_name='welcomeinfo',
            name='promotion_title',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
