# Generated by Django 4.2.18 on 2025-01-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makebooking',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
