# Generated by Django 4.2.18 on 2025-01-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_makebooking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makebooking',
            name='user',
        ),
    ]
