# Generated by Django 4.2.18 on 2025-01-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Side', 'Side'), ('Dessert', 'Dessert'), ('Mains', 'Mains'), ('Drink', 'Drink')], max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
