# Generated by Django 4.2.18 on 2025-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Side', 'Side'), ('Dessert', 'Dessert'), ('Mains', 'Mains'), ('Drink', 'Drink')], max_length=15),
        ),
    ]
